/**
 * 本地化系统 — 中英双语支持
 */

/** @type {'zh'|'en'} */
let _lang = 'zh';

const STRINGS = {
  // ===== 标题 & UI =====
  title:            { zh: '刘邦人生',          en: 'Rise of Liu Bang' },
  subtitle:         { zh: '秦末乱世 · 像素RPG', en: 'Fall of Qin · Pixel RPG' },
  press_start:      { zh: '— 按任意键开始 —',  en: '— Press Any Key —' },
  loading:          { zh: '史册翻动中...',      en: 'Opening the annals...' },
  menu:             { zh: '菜  单',            en: 'M E N U' },
  resume:           { zh: '继续游戏',          en: 'Resume' },
  inventory:        { zh: '背包',              en: 'Inventory' },
  quests:           { zh: '任务',              en: 'Quests' },
  save:             { zh: '存档',              en: 'Save' },
  back_title:       { zh: '返回标题',          en: 'Title Screen' },
  empty_bag:        { zh: '空空如也...',       en: 'Empty...' },
  no_quests:        { zh: '暂无任务',          en: 'No quests' },

  // ===== 地图名 =====
  map_peixian:      { zh: '沛县',              en: 'Pei County' },
  map_liu_home:     { zh: '刘邦家',            en: 'Liu Bang\'s Home' },
  map_xianya:       { zh: '县衙',              en: 'County Office' },
  map_jiusi:        { zh: '王媪酒肆',          en: 'Wang Ao\'s Tavern' },
  map_mangdang:     { zh: '芒砀山',            en: 'Mt. Mangdang' },
  map_mangdang_deep:{ zh: '芒砀山深处',        en: 'Deep Mt. Mangdang' },
  map_xianyang:     { zh: '咸阳城外',          en: 'Outside Xianyang' },
  map_xianyang_palace:{ zh: '秦王宫',          en: 'Qin Palace' },
  map_hongmen:      { zh: '鸿门',              en: 'Hongmen' },
  map_hongmen_tent: { zh: '鸿门宴大帐',        en: 'Hongmen Feast Tent' },
  map_hanzhong:     { zh: '汉中',              en: 'Hanzhong' },
  map_chencang:     { zh: '陈仓',              en: 'Chencang' },
  map_pengcheng:    { zh: '彭城',              en: 'Pengcheng' },
  map_xingyang:     { zh: '荥阳',              en: 'Xingyang' },
  map_gaixia:       { zh: '垓下',              en: 'Gaixia' },
  map_wujiang:      { zh: '乌江',              en: 'Wujiang River' },
  map_changan:      { zh: '定陶·登基',         en: 'Dingtao·Coronation' },
  map_changle_palace:{ zh: '长乐宫',            en: 'Changle Palace' },
  map_peixian_return:{ zh: '沛县·还乡',         en: 'Pei County·Homecoming' },

  // ===== 传送门标签 =====
  portal_peixian_to_liu_home:         { zh: '刘邦家',          en: 'Liu Bang\'s Home' },
  portal_peixian_to_xianya:           { zh: '县衙',            en: 'County Office' },
  portal_peixian_to_jiusi:            { zh: '酒肆',            en: 'Tavern' },
  portal_peixian_to_mangdang:         { zh: '→芒砀山',         en: '→ Mt. Mangdang' },
  portal_liu_home_to_peixian:         { zh: '出门',            en: 'Exit' },
  portal_xianya_to_peixian:           { zh: '出门',            en: 'Exit' },
  portal_jiusi_to_peixian:            { zh: '出门',            en: 'Exit' },
  portal_mangdang_to_peixian:         { zh: '←回沛县',         en: '← Back to Pei County' },
  portal_mangdang_to_mangdang_deep:   { zh: '深山↓',           en: '↓ Deep Mountain' },
  portal_mangdang_deep_to_mangdang:   { zh: '出洞',            en: 'Leave Cave' },
  portal_mangdang_deep_to_peixian:    { zh: '回沛县(交任务)',   en: 'Return to Pei County (Turn In)' },
  portal_mangdang_deep_to_xianyang:   { zh: '→咸阳',           en: '→ Xianyang' },
  portal_xianyang_to_mangdang_deep:   { zh: '←芒砀山',         en: '← Mt. Mangdang' },
  portal_xianyang_to_xianyang_palace: { zh: '秦王宫↓',         en: '↓ Qin Palace' },
  portal_xianyang_to_hongmen:         { zh: '→鸿门',           en: '→ Hongmen' },
  portal_xianyang_palace_to_xianyang: { zh: '出宫',            en: 'Exit Palace' },
  portal_hongmen_to_xianyang:         { zh: '←咸阳',           en: '← Xianyang' },
  portal_hongmen_to_hongmen_tent:     { zh: '大帐↓',           en: '↓ Feast Tent' },
  portal_hongmen_tent_to_hongmen:     { zh: '出帐',            en: 'Exit Tent' },
  portal_hongmen_tent_to_hanzhong:    { zh: '→汉中',           en: '→ Hanzhong' },
  portal_hanzhong_to_hongmen_tent:    { zh: '←鸿门',           en: '← Hongmen' },
  portal_hanzhong_to_chencang:        { zh: '→陈仓',           en: '→ Chencang' },
  portal_chencang_to_hanzhong:        { zh: '←汉中',           en: '← Hanzhong' },
  portal_chencang_to_pengcheng:       { zh: '→彭城',           en: '→ Pengcheng' },
  portal_pengcheng_to_chencang:       { zh: '←陈仓',           en: '← Chencang' },
  portal_pengcheng_to_xingyang:       { zh: '→荥阳',           en: '→ Xingyang' },
  portal_xingyang_to_pengcheng:       { zh: '←彭城',           en: '← Pengcheng' },
  portal_xingyang_to_gaixia:          { zh: '→垓下',           en: '→ Gaixia' },
  portal_gaixia_to_xingyang:          { zh: '←荥阳',           en: '← Xingyang' },
  portal_gaixia_to_wujiang:           { zh: '→乌江',           en: '→ Wujiang River' },
  portal_wujiang_to_gaixia:           { zh: '←垓下',           en: '← Gaixia' },
  portal_wujiang_to_changan:          { zh: '→定陶',           en: '→ Dingtao' },
  portal_changan_to_wujiang:          { zh: '←乌江',           en: '← Wujiang River' },
  portal_changan_to_changle_palace:   { zh: '→长乐宫',         en: '→ Changle Palace' },
  portal_changle_palace_to_changan:   { zh: '出宫',            en: 'Exit Palace' },
  portal_changle_palace_to_peixian_return: { zh: '→沛县',      en: '→ Pei County' },
  portal_peixian_return_to_changle_palace: { zh: '←长安',      en: '← Chang\'an' },

  // ===== 章节介绍 =====
  intro_peixian:    { zh: '📖 第一章 · 少年刘邦\n公元前256年，沛县丰邑。\n刘邦生于农家，不爱农事，\n好结交豪杰，任泗水亭长。', en: '📖 Chapter 1 · Young Liu Bang\n256 BCE, Pei County.\nBorn a farmer, Liu Bang preferred\nthe company of heroes.' },
  intro_liu_home:   { zh: '📖 少年刘邦的居所\n刘邦娶了吕雉为妻，\n但天下将乱，安坐家中\n的日子不多了。', en: '📖 Liu Bang\'s Home\nHe married Lü Zhi,\nbut the realm is crumbling.\nPeaceful days are numbered.' },
  intro_xianya:     { zh: '📖 县衙\n亭长虽小，却是刘邦\n踏入仕途的第一步。', en: '📖 County Office\nThe lowly village chief post\nwas Liu Bang\'s first step\ninto officialdom.' },
  intro_jiusi:      { zh: '📖 王媪酒肆\n刘邦常在此与萧何、曹参\n饮酒议事，结交豪杰。', en: '📖 Wang Ao\'s Tavern\nLiu Bang often drank here\nwith Xiao He and Cao Shen,\nforging lifelong bonds.' },
  intro_mangdang:   { zh: '📖 第二章 · 芒砀山斩蛇\n刘邦奉命押送刑徒去骊山，\n途中多人逃亡。\n他一不做二不休，释放全部刑徒，\n带部分追随者躲入芒砀山。', en: '📖 Chapter 2 · The White Snake\nOrdered to escort convicts to Mt. Li,\nLiu Bang freed them all and\nbecame an outlaw in Mt. Mangdang.' },
  intro_mangdang_deep:{ zh: '📖 深山之中\n白帝之子化作巨蛇挡道，\n刘邦挥剑斩之——\n从此人称"赤帝之子"。', en: '📖 Deep Mountains\nThe White Emperor\'s son took\nserpent form. Liu Bang slew it —\nthus he was called\n"Son of the Red Emperor."' },
  intro_xianyang:   { zh: '📖 第三章 · 西入咸阳\n刘邦率军西进，一路势如破竹。\n公元前207年，兵临咸阳城下。', en: '📖 Chapter 3 · Into Xianyang\n207 BCE. Liu Bang\'s army\nmarched west, unstoppable,\nto the gates of Xianyang.' },
  intro_xianyang_palace:{ zh: '📖 秦王宫\n秦王子婴素车白马，\n向刘邦献上传国玉玺——\n秦朝，灭亡了。', en: '📖 Qin Palace\nZiying, the last Qin king,\nsurrendered the Imperial Seal.\nThe Qin dynasty had fallen.' },
  intro_hongmen:    { zh: '📖 第四章 · 鸿门宴\n项羽率40万大军入关。', en: '📖 Chapter 4 · Hongmen Feast\nXiang Yu arrived with\nan army of 400,000.' },
  intro_hongmen_tent:{ zh: '📖 鸿门宴大帐\n项庄舞剑，意在沛公——\n中国历史上最著名的饭局。', en: '📖 Hongmen Feast Tent\nXiang Zhuang dances with his sword,\nhis eyes on Liu Bang —\nthe most famous dinner in history.' },
  intro_hanzhong:   { zh: '📖 第五章 · 汉中蛰伏\n萧何月下追韩信。', en: '📖 Chapter 5 · Hanzhong\nXiao He chased Han Xin\nunder the moonlight.' },
  intro_chencang:   { zh: '韩信暗度陈仓！关中全部归汉！', en: 'Han Xin\'s secret march!\nAll of Guanzhong falls to Han!' },
  intro_pengcheng:  { zh: '📖 第六章 · 楚汉争霸\n彭城惨败→荥阳对峙→鸿沟之约。', en: '📖 Chapter 6 · Chu-Han War\nPengcheng defeat → Xingyang stalemate\n→ Treaty of the Hong Canal.' },
  intro_gaixia:     { zh: '📖 第七章 · 垓下决战\n十面埋伏，四面楚歌。', en: '📖 Chapter 7 · Battle of Gaixia\nAmbushes on ten sides,\nChu songs on all four.' },
  intro_wujiang:    { zh: '"天之亡我，我何渡为！"', en: '"Heaven has forsaken me —\nwhy should I cross the river?"' },
  intro_changan:    { zh: '📖 第八章 · 建立汉朝\n刘邦即皇帝位。', en: '📖 Chapter 8 · Founding of Han\nLiu Bang ascends the throne.' },
  intro_changle_palace:{ zh: '📖 第九章 · 皇帝时代\n铲除异姓王，白马之盟。', en: '📖 Chapter 9 · The Emperor\nPurging the vassal kings,\nthe Oath of the White Horse.' },
  intro_peixian_return:{ zh: '📖 第十章 · 大风歌\n还乡沛县。', en: '📖 Chapter 10 · Song of the Great Wind\nHomecoming to Pei County.' },

  // ===== 操作提示 =====
  hint_move:        { zh: '↑↓←→/WASD 移动',  en: '↑↓←→/WASD Move' },
  hint_interact:    { zh: 'T/Enter 互动',      en: 'T/Enter Interact' },
  hint_esc:         { zh: 'Esc 菜单',           en: 'Esc Menu' },
  hint_collect:     { zh: 'T/Enter 采集',      en: 'T/Enter Gather' },

  // ===== NPC 名字 =====
  npc_wangao:       { zh: '王媪',              en: 'Madam Wang' },
  npc_villager:     { zh: '乡民',              en: 'Villager' },
  npc_fan_kuai:     { zh: '樊哙',              en: 'Fan Kuai' },
  npc_lvzhi:        { zh: '吕雉',              en: 'Lü Zhi' },
  npc_xiao_he:      { zh: '萧何',              en: 'Xiao He' },
  npc_cao_shen:     { zh: '曹参',              en: 'Cao Shen' },
  npc_prisoner:     { zh: '刑徒',              en: 'Convict' },
  npc_white_snake:  { zh: '白蛇',              en: 'White Snake' },
  npc_qin_soldier:  { zh: '秦兵',              en: 'Qin Soldier' },
  npc_qin_captain:  { zh: '秦兵什长',         en: 'Qin Sergeant' },
  npc_qin1:         { zh: '秦兵',              en: 'Qin Soldier' },
  npc_qin2:         { zh: '秦兵什长',         en: 'Qin Sergeant' },
  npc_qin3:         { zh: '秦兵',              en: 'Qin Soldier' },
  npc_thief1:       { zh: '地痞',              en: 'Thug' },
  npc_zhang_liang:  { zh: '张良',              en: 'Zhang Liang' },
  npc_villager2:    { zh: '秦民',              en: 'Qin Citizen' },
  npc_ziying:       { zh: '子婴',              en: 'Ziying' },
  npc_fan_kuai2:    { zh: '樊哙',              en: 'Fan Kuai' },
  npc_xiang_bo:     { zh: '项伯',              en: 'Xiang Bo' },
  npc_soldier1:     { zh: '楚兵',              en: 'Chu Soldier' },
  npc_xiang_yu:     { zh: '项羽',              en: 'Xiang Yu' },
  npc_xiang_zhuang: { zh: '项庄',              en: 'Xiang Zhuang' },
  npc_fan_zeng:     { zh: '范增',              en: 'Fan Zeng' },
  npc_qin_guard1:   { zh: '秦兵',              en: 'Qin Guard' },
  npc_qin_guard2:   { zh: '秦兵',              en: 'Qin Guard' },
  npc_chu_guard1:   { zh: '楚兵',              en: 'Chu Guard' },
  npc_xiang_zhuang_enemy:{ zh: '项庄',         en: 'Xiang Zhuang' },
  npc_xiao_he2:     { zh: '萧何',              en: 'Xiao He' },
  npc_hanxin:       { zh: '韩信',              en: 'Han Xin' },
  npc_zhang_han:    { zh: '章邯',              en: 'Zhang Han' },
  npc_fan_kuai3:    { zh: '樊哙',              en: 'Fan Kuai' },
  npc_zhang_han_enemy:{ zh: '章邯',             en: 'Zhang Han' },
  npc_qin_soldier_c1:{ zh: '秦兵',              en: 'Qin Soldier' },
  npc_chen_ping:    { zh: '陈平',              en: 'Chen Ping' },
  npc_ji_xin:       { zh: '纪信',              en: 'Ji Xin' },
  npc_peng_yue:     { zh: '彭越',              en: 'Peng Yue' },
  npc_chu_elite1:   { zh: '楚军精锐',          en: 'Chu Elite' },
  npc_chu_elite2:   { zh: '楚军精锐',          en: 'Chu Elite' },
  npc_chu_captain:  { zh: '楚军守将',          en: 'Chu Captain' },
  npc_hanxin2:      { zh: '韩信',              en: 'Han Xin' },
  npc_zhang_liang2: { zh: '张良',              en: 'Zhang Liang' },
  npc_xiang_yu2:    { zh: '项羽',              en: 'Xiang Yu' },
  npc_boatman:      { zh: '亭长',              en: 'Boatman' },
  npc_hanxin3:      { zh: '韩信',              en: 'Han Xin' },
  npc_lou_jing:     { zh: '娄敬',              en: 'Lou Jing' },
  npc_zhang_liang3: { zh: '张良',              en: 'Zhang Liang' },
  npc_liu_bang_old: { zh: '刘邦',              en: 'Liu Bang' },
  npc_lvhou:        { zh: '吕后',              en: 'Empress Lü' },
  npc_shusun_tong:  { zh: '叔孙通',            en: 'Shusun Tong' },
  npc_liu_bang_final:{ zh: '刘邦',             en: 'Liu Bang' },
  npc_elder:        { zh: '父老',              en: 'Elder' },
  npc_liu_bang_last:{ zh: '刘邦',              en: 'Liu Bang' },
  npc_chu_guard_g1: { zh: '楚军护卫',          en: 'Chu Guard' },
  npc_chu_guard_g2: { zh: '楚军护卫',          en: 'Chu Guard' },

  // ===== 对话 =====
  dlg_wangao:       { zh: '刘季这孩子从小就有大志，\n如今做了亭长，也算出息了。',
                      en: 'Young Liu Bang always had ambition.\nNow he\'s a village chief — not bad.' },
  dlg_villager:     { zh: '听说陈胜吴广在大泽乡起义了！\n天下要乱了…',
                      en: 'Chen Sheng and Wu Guang have risen up!\nThe realm is falling into chaos...' },
  dlg_fan_kuai:     { zh: '刘邦兄弟！我是屠狗的樊哙，\n要干大事记得叫上我！',
                      en: 'Brother Liu! I\'m Fan Kuai the butcher.\nWhen you make your move, count me in!' },
  dlg_lvzhi:        { zh: '夫君，外面世道不太平，\n万事要小心。',
                      en: 'My husband, the world is troubled.\nPlease be careful out there.' },
  dlg_xiao_he_start:{ zh: '刘邦，县令让你押送一批刑徒去骊山修陵。\n这是苦差事，但办好了说不定能升迁。',
                      en: 'Liu Bang, the magistrate orders you\n to escort convicts to Mt. Li.\nDo well and you may rise in rank.' },
  dlg_xiao_he_quest:{ zh: '这一路凶险，到达芒砀山深处\n就算完成任务。去吧！',
                      en: 'The road is dangerous. Reach deep\nMt. Mangdang to complete the mission.' },
  dlg_xiao_he_done: { zh: '你做到了！虽然刑徒逃了大半…\n但乱世之中，这也未必是坏事。',
                      en: 'You made it! Many convicts escaped...\nBut in these times, that may be a blessing.' },
  dlg_cao_shen:     { zh: '刘邦兄！来喝酒！\n我虽是狱掾，但这世道…\n咱们迟早得干一番大事！',
                      en: 'Brother Liu! Drink with me!\nI\'m just a jail warden now, but...\nWe\'re destined for greater things!' },
  dlg_prisoner:     { zh: '亭长仁义，放我们一条生路。\n我等愿追随左右！',
                      en: 'You spared us, chief. We are forever\nin your debt. We will follow you!' },
  dlg_snake:        { zh: '（一条巨大的白蛇挡住了去路！\n此乃白帝之子，斩之可立威！）\n\n📖 典故：刘邦醉酒夜行，路遇白蛇挡道，\n挥剑斩之。后有老妇人哭诉：\n"吾子白帝子也，化为蛇，\n今赤帝子斩之。"\n从此人们传说刘邦乃赤帝之子下凡。',
                      en: '(A giant white snake blocks the path!)\n\n📖 Legend: Liu Bang, drunk at night,\nencountered a giant white snake and slew it.\nLater, an old woman wept: "My son,\nthe White Emperor\'s child, was slain by\nthe Red Emperor\'s son."\nThus, people believed Liu Bang was\ndivinely chosen — the Red Emperor\'s heir.' },
  dlg_white_snake_win:{ zh: '刘邦拔剑斩向白蛇！\n一道白光冲天而起——\n赤帝之子斩白帝之子！\n从此天下皆知刘邦乃天命所归！',
                      en: 'Liu Bang drew his sword!\nA white light shot to heaven —\nThe Red Emperor slays the White!\nFrom this day, all knew:\nHeaven had chosen Liu Bang.' },
  dlg_qin_soldier:  { zh: '站住！你是逃犯刘邦！\n奉旨缉拿归案！',
                      en: 'Halt! You are the fugitive Liu Bang!\nSurrender by imperial order!' },
  dlg_qin_captain:  { zh: '反贼！竟敢私放刑徒！\n拿下他！',
                      en: 'Rebel! You freed the convicts!\nSeize him!' },
  dlg_zhang_liang:  { zh: '沛公！咸阳就在眼前。\n记住——约法三章，得民心者得天下。',
                      en: 'Lord Pei! Xianyang lies ahead.\nRemember — win the people, win the realm.' },
  dlg_qin_citizen:  { zh: '秦法严苛已久，沛公若能\n废除苛法，我等愿效犬马之劳！',
                      en: 'The Qin laws have oppressed us long.\nAbolish them and we will serve you!' },
  dlg_xiang_bo:     { zh: '（低声）张良兄让我来报信——\n项羽明日要攻打汉军！',
                      en: '(Whispering) Zhang Liang sent me —\nXiang Yu attacks tomorrow!' },
  dlg_chu_soldier:  { zh: '项王有令，明日犒赏三军，\n一举击破刘邦！',
                      en: 'The Hegemon-King orders —\n tomorrow we crush Liu Bang!' },
  // ===== 历史典故对话 =====
  dlg_three_laws:   { zh: '📖 约法三章\n刘邦入咸阳后，与关中父老约定：\n"杀人者死，伤人及盗抵罪。"\n其余秦朝严刑峻法全部废除。\n关中百姓大喜，"唯恐沛公不为秦王"。\n——这就是"约法三章"的由来。',
                      en: '📖 Three Articles of Law\nUpon entering Xianyang, Liu Bang declared:\n"Murderers shall be executed;\n assault and theft shall be punished."\nAll other harsh Qin laws were abolished.\nThe people rejoiced — this was how\nLiu Bang won the hearts of Guanzhong.' },
  dlg_hongmen_feast: { zh: '📖 鸿门宴\n公元前206年，项羽在新丰鸿门设宴\n款待刘邦。席间，范增多次举玉玦\n示意项羽动手杀死刘邦。\n项庄借口舞剑助兴，剑锋直指沛公。\n危急关头，项伯起身对舞，以身相护。\n张良急召樊哙闯帐，刘邦借如厕之名\n从小路逃回灞上。\n——"项庄舞剑，意在沛公"流传至今。',
                      en: '📖 The Hongmen Feast\n206 BCE. Xiang Yu hosted Liu Bang\nat Hongmen. Fan Zeng signaled Xiang Yu\nto kill Liu Bang. Xiang Zhuang danced\nwith his sword aimed at Liu Bang.\nXiang Bo shielded him. Fan Kuai burst in.\nLiu Bang escaped through the privy.\n— "Xiang Zhuang dances with his sword,\nhis eyes on Liu Bang" became a proverb.' },
  dlg_chencang:     { zh: '📖 明修栈道，暗度陈仓\n韩信拜将后，一面派樊哙大张旗鼓\n修复烧毁的褒斜道栈道，麻痹关中三王；\n一面亲率主力秘密沿故道绕行，\n突然出现在陈仓城下。\n章邯措手不及，大败而逃。\n——此计被收入三十六计第八计。',
                      en: '📖 Secret March to Chencang\nHan Xin had Fan Kuai loudly repair\nthe burned plank roads — a decoy.\nMeanwhile, he led the main army\nthrough a hidden mountain path\nand ambushed Chencang.\nZhang Han was caught off guard.\n— "Deceive the enemy with a feint,\nstrike where least expected."' },

  // ===== NPC 专属对话 =====
  dlg_ziying:       { zh: '（秦王子婴素车白马，系颈以组）\n秦朝…亡了。\n我将玉玺交予沛公。',
                      en: '(Ziying, in plain white chariot with rope\naround his neck.) The Qin... has fallen.\nI surrender the Imperial Seal to you.' },
  dlg_fan_kuai2:    { zh: '大哥！这秦宫财宝如山，\n美女如云。但张良说得对——\n贪图享乐就是走秦朝老路！',
                      en: 'Brother! The Qin palace overflows\nwith gold and beauties. But Zhang Liang\nis right — indulgence follows Qin\'s path!' },
  dlg_xiang_yu:     { zh: '沛公远来，请上座。\n（眼神中藏着杀机）',
                      en: 'Lord Pei has come far — take the seat of honor.\n(His eyes hide murderous intent.)' },
  dlg_xiang_zhuang: { zh: '（拔剑起舞）\n军中无以为乐，请以剑舞助兴！\n（剑锋直指沛公！）',
                      en: '(Draws his sword and dances.)\nLet me entertain our guest with a sword dance!\n(The blade points straight at Liu Bang!)' },
  dlg_fan_zeng:     { zh: '（举玉玦示意三次，项羽不应）\n范增摔碎玉斗："竖子不足与谋！\n夺项王天下者，必沛公也！"',
                      en: '(He raised his jade ring three times —\nXiang Yu ignored him.) Fan Zeng smashed his\ncup: "Foolish boy! He who takes your throne\nwill surely be this Lord of Pei!"' },
  dlg_xiao_he2:     { zh: '大王，我追回了一个人——\n韩信！他是国士无双，\n必能助大王争夺天下！',
                      en: 'My King, I have brought back a man —\nHan Xin! He is a peerless talent\nwho can help you win the realm!' },
  dlg_hanxin:       { zh: '（登坛对——汉中对）\n项王虽勇，匹夫之勇耳。\n大王若举兵东出，\n三秦可传檄而定！',
                      en: '(The Hanzhong Strategy.)\nXiang Yu is brave, but only as one man.\nIf Your Majesty marches east,\nthe Three Qin kingdoms will fall.' },
  dlg_zhang_han:    { zh: '什么？！汉军不是还在修栈道吗，\n怎么已经打到陈仓了？！\n——韩信！你好狠的计策！',
                      en: 'What?! The Han army was still\nrepairing the plank roads —\nhow are they already at Chencang?!\nHan Xin! What a ruthless stratagem!' },
  dlg_fan_kuai3:    { zh: '哈哈哈！我们在那边大张旗鼓修栈道，\n章邯果然中计了！\n韩信将军真是神机妙算！',
                      en: 'Ha ha ha! We made a great show of\nrepairing those plank roads —\nZhang Han fell for it completely!\nGeneral Han Xin is a genius!' },
  dlg_chen_ping:    { zh: '大王！彭城虽破，但楚军主力尚存。\n臣有一计——反间！\n项羽多疑，离间他与范增、钟离眜。',
                      en: 'My King! Pengcheng has fallen,\nbut Chu\'s main force remains.\nI have a plan — sow discord!\nXiang Yu is suspicious.' },
  dlg_ji_xin:       { zh: '大王！荥阳若守不住，\n臣愿假扮大王开城出降，\n大王可从西门突围。',
                      en: 'My King! If Xingyang cannot hold,\nlet me impersonate you and surrender —\nwhile you escape through the west gate.' },
  dlg_peng_yue:     { zh: '汉王！我在楚军后方不断骚扰，\n断了他们的粮道。\n项羽疲于奔命，成皋必将易手！',
                      en: 'King of Han! I harry the Chu rear\nand cut their supply lines.\nXiang Yu is exhausted — Chenggao will fall!' },
  dlg_hanxin2:      { zh: '大王！臣设十面埋伏之计，\n楚军已插翅难飞。\n今夜请四面楚歌，瓦解楚军士气。',
                      en: 'My King! I have laid ambushes on ten sides.\nThe Chu army is trapped.\nTonight — Chu songs shall break their will.' },
  dlg_zhang_liang2: { zh: '我已命汉军齐唱楚歌。\n楚军听到家乡歌声，思乡心切，\n军心必溃。',
                      en: 'I have ordered the Han army to sing Chu songs.\nWhen Chu soldiers hear their homeland\'s music,\ntheir morale will crumble.' },
  dlg_xiang_yu2:    { zh: '（独立乌江边，仰天长叹）\n天之亡我，我何渡为！\n籍与江东子弟八千人渡江而西，\n今无一人还——\n纵江东父兄怜而王我，\n我何面目见之？',
                      en: '(Alone by the Wujiang River.)\nHeaven has forsaken me —\nwhy should I cross?\nEight thousand sons of Jiangdong crossed\nwith me — now not one lives.\nHow could I face their fathers?' },
  dlg_boatman:      { zh: '大王！江东虽小，地方千里，\n众数十万，亦足王也！\n请大王急渡！',
                      en: 'My King! Jiangdong may be small,\nbut it spans a thousand li.\nPlease — cross the river!' },
  dlg_hanxin3:      { zh: '臣楚王韩信，率七位诸侯王，\n联名劝进——请汉王即皇帝位！\n国号"汉"，定都洛阳！',
                      en: 'I, Han Xin, King of Chu,\nwith seven vassal kings, jointly petition —\nplease ascend the imperial throne!\nThe dynasty: "Han," capital: Luoyang!' },
  dlg_lou_jing:     { zh: '陛下！臣一介戍卒，斗胆进言：\n洛阳四面受敌，不宜为都。\n关中"被山带河，四塞以为固"，\n沃野千里，天府之国！',
                      en: 'Your Majesty! A humble conscript dares\nspeak: Luoyang is vulnerable on all sides.\nGuanzhong is a natural fortress —\na land of plenty, the Celestial Granary!' },
  dlg_zhang_liang3: { zh: '娄敬说得对！新都取名——\n"长安"！长治久安之意。\n关中金城千里，天府之国。',
                      en: 'Lou Jing is right! We shall call\nthe new capital "Chang\'an" —\nEternal Peace through good governance.' },
  dlg_liu_bang_old: { zh: '（坐在龙椅上，威严中透着疲惫）\n吾以布衣提三尺剑取天下，\n此非天命乎？\n……非刘氏而王者，天下共击之！',
                      en: '(On the dragon throne, majestic yet weary.)\nI, a commoner, won the realm with a sword —\nis this not Heaven\'s mandate?' },
  dlg_lvhou:        { zh: '陛下，异姓诸侯王势力太大，\n不可不除。韩信、彭越、英布…\n妾身来办。',
                      en: 'Your Majesty, the vassal kings\nwield too much power. Han Xin,\nPeng Yue, Ying Bu... Leave them to me.' },
  dlg_shusun_tong:  { zh: '陛下！臣为汉朝制定朝仪。\n演练数月后，群臣列队，\n无人敢喧哗失礼。\n刘邦感叹："吾乃今日知为皇帝之贵也！"',
                      en: 'Your Majesty! I have established court ritual.\nThe officials now line up in perfect silence.\nLiu Bang: "Only now do I know the true\ndignity of an emperor!"' },
  dlg_liu_bang_final:{ zh: '（置酒沛宫，召故人父老子弟纵酒，\n发沛中儿得百二十人，教之歌）\n大风起兮云飞扬——\n威加海内兮归故乡——\n安得猛士兮守四方！\n（起舞，泣数行下）',
                      en: '(He feasted the elders of Pei, gathered 120\nyouths, taught them to sing:)\nA great wind rises, clouds fly high —\nMy might has conquered all beneath the sky —\nI return home — where are the warriors\nto guard my realm on every side?\n(He rose and danced, tears streaming.)' },
  dlg_liu_bang_last:{ zh: '游子悲故乡。\n吾虽都关中，万岁后，\n吾魂魄犹乐思沛。\n\n从农家少年到大汉天子——\n此乃天命，亦乃人力。\n\n—— 全篇完 ——',
                      en: 'A wanderer yearns for his homeland.\nThough I dwell in the capital,\nmy spirit will always return to Pei.\n\nFrom farm boy to Emperor of Han —\nthe will of Heaven, and the work of men.\n\n— THE END —' },

  // ===== 任务交互 / 剧情 =====
  dlg_xiao_he_go:   { zh: '快去芒砀山深处！到了自会有收获。', en: 'Hurry to deep Mt. Mangdang! You will be rewarded.' },
  dlg_xiao_he_later:{ zh: '乱世将至，保重。', en: 'Chaos is coming. Stay safe.' },
  dlg_snake_intro:  { zh: '前面有条大白蛇挡路！\n亭长若能斩杀此蛇，\n必能树立威望！', en: 'A giant white snake blocks the path!\nSlay it and your renown will soar!' },
  dlg_snake_go:     { zh: '那白蛇就在东边的路上！斩了它！', en: 'The white snake lies on the eastern path. Go slay it!' },
  dlg_snake_spare:  { zh: '白蛇低首，化作白光消散。众人惊呼：赤帝之子！', en: 'The white snake bows and vanishes in light.\n"Son of the Red Emperor!" the crowd cries.' },
  dlg_need_atk:     { zh: '攻击力不够！去完成押送任务获得赤霄剑。', en: 'Not strong enough! Complete the escort quest for the Red Dawn Blade.' },
  dlg_three_laws_go:{ zh: '张良：沛公！请入秦王宫，\n接受子婴投降，颁布约法三章！\n进入王宫自会获得封赏。', en: 'Zhang Liang: Lord Pei! Enter Qin Palace,\naccept Ziying\'s surrender, and proclaim\nthe Three Laws!' },
  dlg_feast_go:     { zh: '项伯：（急切）快走！\n明日项羽就要动手了！\n到汉中就安全了，快！', en: 'Xiang Bo: (Urgently) Leave now!\nXiang Yu will strike tomorrow!\nEscape to Hanzhong — quickly!' },
  dlg_chencang_go:  { zh: '韩信：明修栈道，暗度陈仓！\n抵达陈仓之日，\n就是关中归汉之时！', en: 'Han Xin: Repair openly — march secretly!\nWhen you reach Chencang,\nGuanzhong is ours!' },
  dlg_xingyang_go:  { zh: '陈平：荥阳守将必须击败！\n拿下荥阳，敖仓粮仓就是我们的！', en: 'Chen Ping: Defeat the Chu captain!\nCapture Xingyang and the Aocang granary!' },
  dlg_gaixia_go:    { zh: '韩信：十面埋伏已成，\n请大王亲至乌江，\n见证项羽的末路。', en: 'Han Xin: The trap is set.\nCome to Wujiang River and\nwitness Xiang Yu\'s final hour.' },
  dlg_coronation_go:{ zh: '韩信：天下已定，\n请汉王移驾定陶，\n即皇帝位！', en: 'Han Xin: The realm is pacified.\nProceed to Dingtao and ascend the throne!' },

  // ===== 任务 =====
  quest_escort_title:  { zh: '押送刑徒',          en: 'Escort the Convicts' },
  quest_escort_desc:   { zh: '将刑徒押送至芒砀山深处', en: 'Escort convicts to deep Mt. Mangdang' },
  quest_snake_title:   { zh: '斩蛇立威',          en: 'Slay the White Snake' },
  quest_snake_desc:    { zh: '在芒砀山斩杀白蛇，树立威望', en: 'Slay the white snake to gain renown' },
  quest_three_laws_title:{ zh: '约法三章',        en: 'Three Articles of Law' },
  quest_three_laws_desc: { zh: '进入秦王宫，颁布约法三章', en: 'Enter Qin Palace, declare the Three Laws' },
  quest_feast_title:   { zh: '鸿门脱身',          en: 'Escape Hongmen' },
  quest_feast_desc:    { zh: '从鸿门宴安全抵达汉中', en: 'Escape Hongmen Feast to Hanzhong' },
  quest_chencang_title:{ zh: '暗度陈仓',          en: 'Secret March' },
  quest_chencang_desc: { zh: '抵达陈仓，奇袭三秦', en: 'Reach Chencang, ambush the Three Qin' },
  quest_xingyang_title:{ zh: '攻占荥阳',          en: 'Take Xingyang' },
  quest_xingyang_desc: { zh: '击败荥阳楚军守将',   en: 'Defeat the Chu captain at Xingyang' },
  quest_gaixia_title:  { zh: '垓下决战',          en: 'Battle of Gaixia' },
  quest_gaixia_desc:   { zh: '追击项羽至乌江',     en: 'Pursue Xiang Yu to Wujiang River' },
  quest_coronation_title:{ zh: '登基称帝',        en: 'Coronation' },
  quest_coronation_desc:{ zh: '抵达定陶，登基称帝', en: 'Reach Dingtao for the coronation' },

  // ===== 选择 =====
  choice_accept:    { zh: '接受',        en: 'Accept' },
  choice_decline:   { zh: '再想想',      en: 'Not now' },
  choice_attack:    { zh: '迎战！',      en: 'Fight!' },
  choice_flee:      { zh: '暂避',        en: 'Fall back' },
  choice_slay:      { zh: '好！斩蛇立威！', en: 'Yes! Slay the snake!' },
  choice_around:    { zh: '绕道而行',    en: 'Go around' },
  choice_yes:       { zh: '诺！',        en: 'Yes!' },
  choice_thanks:    { zh: '多谢！',      en: 'Thank you!' },
  choice_strike:    { zh: '出击！',      en: 'Attack!' },
  choice_chase:     { zh: '追击！',      en: 'Pursue!' },
  choice_crown:     { zh: '登基！',      en: 'Ascend!' },
  choice_slay_snake:{ zh: '⚔ 斩杀白蛇',   en: '⚔ Slay the Snake' },
  choice_spirit:    { zh: '✨ 以赤帝之名感召', en: '✨ Invoke the Red Emperor' },
  choice_fight_5:   { zh: '⚔ 攻击！(需攻击≥5)', en: '⚔ Attack! (ATK≥5 needed)' },
  choice_retreat:   { zh: '🏃 暂避',     en: '🏃 Fall Back' },
  choice_wait:      { zh: '等等',        en: 'Wait' },

  // ===== 战斗/结果 =====
  battle_snake_win: { zh: '刘邦拔剑斩向白蛇！\n一道白光冲天而起——\n从此天下皆知刘邦之名！',
                      en: 'Liu Bang drew his sword and struck!\nA white light shot up to heaven —\nFrom this day, all knew his name!' },
  battle_qin_win:   { zh: '击败了秦兵！\n乱世之中，唯有刀剑说话。',
                      en: 'Qin soldier defeated!\nIn chaos, only the blade speaks.' },
  snake_drop:       { zh: '获得了白蛇之血（赤帝之证）', en: 'Obtained White Snake Blood (Red Emperor\'s Proof).' },
  qin_drop:         { zh: '缴获了秦军令牌',   en: 'Looted a Qin army token.' },

  // ===== 任务状态 =====
  st_available:     { zh: '未接',        en: 'New' },
  st_active:        { zh: '进行中',      en: 'Active' },
  st_completed:     { zh: '✓可交',       en: '✓Done' },
  st_claimed:       { zh: '已完成',      en: 'Completed' },

  // ===== 物品 =====
  item_herb:        { zh: '草药',        en: 'Herb' },
  item_herb_desc:   { zh: '山中采集的药草',     en: 'Herb gathered in the mountains.' },
  item_sword:       { zh: '赤霄剑',      en: 'Red Dawn Blade' },
  item_sword_desc:  { zh: '传说中斩白蛇的宝剑', en: 'The legendary sword that slew the white snake.' },
  item_token:       { zh: '秦军令牌',   en: 'Qin Army Token' },
  item_token_desc:  { zh: '击败秦兵缴获的令牌', en: 'Taken from a defeated Qin soldier.' },
  item_blood:       { zh: '赤帝之证',   en: 'Red Emperor\'s Proof' },
  item_blood_desc:  { zh: '斩白蛇所得，赤帝血脉之证', en: 'Proof of the Red Emperor\'s bloodline.' },

  // ===== 采集 =====
  gather_herb:      { zh: '采集到一株草药！',    en: 'Found a herb!' },
  gather_nothing:   { zh: '这里什么也没有。',    en: 'Nothing here.' },
};

// 需要参数化的字符串
const FORMATS = {
  herb_count:       (n) => ({ zh: `你有${n}株草药`, en: `You have ${n} herb(s).` }),
  slay_progress:    (r, t) => ({ zh: `还剩${t - r}个目标，加油！`, en: `${t - r} targets remaining!` }),
  need_more:        (n) => ({ zh: `凑够${n}株可以打造赤霄剑。`, en: `Collect ${n} to forge the Red Dawn Blade.` }),
};

/** 获取本地化字符串 */
export function t(key, ...args) {
  const entry = STRINGS[key];
  if (!entry) return key;
  if (args.length > 0) {
    const fmt = FORMATS[key];
    if (fmt) return fmt(...args)[_lang];
  }
  return entry[_lang] || entry['zh'] || key;
}

/** 获取/设置当前语言 */
export function lang(newLang) {
  if (newLang) { _lang = newLang; localStorage.setItem('rpg_lang', newLang); }
  return _lang;
}

/** 初始化语言（从 localStorage 恢复） */
export function initLang() {
  const saved = localStorage.getItem('rpg_lang');
  if (saved === 'en' || saved === 'zh') _lang = saved;
}

export default { t, lang, initLang };
